name: Lint

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          with:
            fetch-depth: 0


      # Refer to this documentation https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache

          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}

          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        id: 'install-dependencies'
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ github.token }}
          # Enable linters
          eslint: true
          prettier: true