name: ESLint and Prettier Linting

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: ESLint Linting
        run: npx eslint .
        # You may need to adjust the paths if your code is in a different directory

      - name: Prettier Linting
        run: npx prettier --check .
        # You may need to adjust the paths if your code is in a different directory
